---
language: go

os: linux

install:
  - go get -t -v ./...

script:
  - go test -v ./...
  - export GO_LDFLAGS="-s -w -X \"main.timestamp=$(date +%Y-%m-%dT%H:%M:%S%z)\"
    -X \"main.version=${TRAVIS_TAG:-$TRAVIS_COMMIT}\""
  - env GOOS=darwin GOARCH=386 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.darwin_386.tar.gz slacker
  - env GOOS=darwin GOARCH=amd64 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.darwin_amd64.tar.gz slacker
  - env GOOS=dragonfly GOARCH=amd64 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.dragonfly_amd64.tar.gz
    slacker
  - env GOOS=freebsd GOARCH=386 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.freebsd_386.tar.gz slacker
  - env GOOS=freebsd GOARCH=amd64 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.freebsd_amd64.tar.gz slacker
  - env GOOS=freebsd GOARCH=arm GOARM=6 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.freebsd_armv6.tar.gz slacker
  - env GOOS=freebsd GOARCH=arm GOARM=7 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.freebsd_armv7.tar.gz slacker
  - env GOOS=freebsd GOARCH=arm go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.freebsd_armv8.tar.gz slacker
  - env GOOS=linux GOARCH=386 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.linux_386.tar.gz slacker
  - env GOOS=linux GOARCH=amd64 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.linux_amd64.tar.gz slacker
  - env GOOS=linux GOARCH=arm GOARM=5 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.linux_armv5.tar.gz slacker
  - env GOOS=linux GOARCH=arm GOARM=6 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.linux_armv6.tar.gz slacker
  - env GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.linux_armv7.tar.gz slacker
  - env GOOS=linux GOARCH=arm go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.linux_armv8.tar.gz slacker
  - env GOOS=linux GOARCH=arm64 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.linux_arm64.tar.gz slacker
  - env GOOS=linux GOARCH=mips64 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.linux_mips64.tar.gz slacker
  - env GOOS=linux GOARCH=mips64le go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.linux_mips64le.tar.gz slacker
  - env GOOS=linux GOARCH=ppc64 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.linux_ppc64.tar.gz slacker
  - env GOOS=linux GOARCH=ppc64le go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.linux_ppc64le.tar.gz slacker
  - env GOOS=linux GOARCH=s390x go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.linux_s390x.tar.gz slacker
  - env GOOS=netbsd GOARCH=386 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.netbsd_386.tar.gz slacker
  - env GOOS=netbsd GOARCH=amd64 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.netbsd_amd64.tar.gz slacker
  - env GOOS=netbsd GOARCH=arm GOARM=6 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.netbsd_armv6.tar.gz slacker
  - env GOOS=netbsd GOARCH=arm GOARM=7 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.netbsd_armv7.tar.gz slacker
  - env GOOS=netbsd GOARCH=arm go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.netbsd_armv8.tar.gz slacker
  - env GOOS=openbsd GOARCH=386 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.openbsd_386.tar.gz slacker
  - env GOOS=openbsd GOARCH=amd64 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.openbsd_amd64.tar.gz slacker
  - env GOOS=openbsd GOARCH=arm GOARM=6 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.openbsd_armv6.tar.gz slacker
  - env GOOS=openbsd GOARCH=arm GOARM=7 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.openbsd_armv7.tar.gz slacker
  - env GOOS=openbsd GOARCH=arm go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.openbsd_arm.tar.gz slacker
  - env GOOS=solaris GOARCH=amd64 go build -ldflags="${GO_LDFLAGS}" &&
    tar czvf slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.solaris_amd64.tar.gz slacker
  - env GOOS=windows GOARCH=386 go build -ldflags="${GO_LDFLAGS}" -o slacker.exe
    && zip -9 slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.windows_386.zip slacker.exe
  - env GOOS=windows GOARCH=amd64 go build -ldflags="${GO_LDFLAGS}" -o
    slacker.exe && zip -9
    slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.windows_amd64.zip slacker.exe
  - sha256sum *.tar.gz *.zip >
    slacker-${TRAVIS_TAG:-$TRAVIS_COMMIT}.sha256sum.txt

go:
  - 1.8.x

deploy:
  provider: releases
  api_key:
    secure: >
        Vapx2krBEg9Gc5uPLDYKC0Z4V008U2LSydRjgm/DxN5I62uT1H5/QkNhDAVaoizmpPJcF
        ZlIdlyxCkpVAuVG1kONgcccR+Jzib90ItiQrH309hWqP7X0IApw9FTz98hMWTJJn6EA9X
        Clo5wK/NcCKt9W4CJ+bM10UU3tg81IByyipjwaPuA1EVSaOIuWmKSnv+1USkx1+MZARhw
        Kr1S4fuVpNWVp8W7wBlP27VKN2K8pxc5xgO5JkYx6U5ONc2Y5uJX5QWPPcYVWgjqOKBUk
        ypSECTW0nTHPq4wiiCw+E/vpf13Zr0o6IDWvWBz3N6NJAMRZj8/94X1BoWt4W4mE0uSwc
        ngYQS4OYp0NSKdJgfNnpi9MY+Qfml+3gybNnCancT9bw7Ce3dd2lGnhIsxTMXtItbs3fR
        w2I0BnX933RhbUPzpQ4mde70Z3NdKbrG/o6I8gyw/CgjosLqB0PXpb6w2nqDzkKaRqYLu
        PVAqWcCVtgk4IG17xk2cBtR0uZsnxqBhBNmaOH9tcJBa9njYkN9kImmlnziKw4cH34scz
        6w0t9TUNxuxAmbSkdxeM1aRCE6TKM35GUnkZOJYoKt37FfMHbyrbxy1Qi6kGJWJ9pHj68
        VsmA2Rg8bdoNyeabJcu/vjM0FalMsyVeIIIP4egpIo0rmniZI2Y1+NGlqAqkR8=
  skip_cleanup: true
  file_glob: true
  file:
    - "slacker-*.sha256sum.txt"
    - "slacker-*.tar.gz"
    - "slacker-*.zip"
  "on":
    repo: logic/slacker
    tags: true
