---
os: linux

language: go

go:
  - 1.8.x

env:
  - GOOS=darwin GOARCH=386
  - GOOS=darwin GOARCH=amd64
  - GOOS=dragonfly GOARCH=amd64
  - GOOS=freebsd GOARCH=386
  - GOOS=freebsd GOARCH=amd64
  - GOOS=freebsd GOARCH=arm GOARM=6
  - GOOS=freebsd GOARCH=arm GOARM=7
  - GOOS=freebsd GOARCH=arm
  - GOOS=linux GOARCH=386
  - GOOS=linux GOARCH=amd64
  - GOOS=linux GOARCH=arm GOARM=5
  - GOOS=linux GOARCH=arm GOARM=6
  - GOOS=linux GOARCH=arm GOARM=7
  - GOOS=linux GOARCH=arm
  - GOOS=linux GOARCH=arm64
  - GOOS=linux GOARCH=mips64
  - GOOS=linux GOARCH=mips64le
  - GOOS=linux GOARCH=ppc64
  - GOOS=linux GOARCH=ppc64le
  - GOOS=linux GOARCH=s390x
  - GOOS=netbsd GOARCH=386
  - GOOS=netbsd GOARCH=amd64
  - GOOS=netbsd GOARCH=arm GOARM=6
  - GOOS=netbsd GOARCH=arm GOARM=7
  - GOOS=netbsd GOARCH=arm
  - GOOS=openbsd GOARCH=386
  - GOOS=openbsd GOARCH=amd64
  - GOOS=openbsd GOARCH=arm GOARM=6
  - GOOS=openbsd GOARCH=arm GOARM=7
  - GOOS=openbsd GOARCH=arm
  - GOOS=solaris GOARCH=amd64
  - GOOS=windows GOARCH=386 EXT=".exe" PKGCMD="zip -9" PKGEXT=".zip"
  - GOOS=windows GOARCH=amd64 EXT=".exe" PKGCMD="zip -9" PKGEXT=".zip"

install:
  - go get -t -v ./...

script:
  - export TIME="$(date +%Y-%m-%dT%H:%M:%S%z)"
  - export VER="${TRAVIS_TAG:-$TRAVIS_COMMIT}"
  - export PKGCMD="${PKGCMD:-tar zcvf}"
  - export PKGEXT="${PKGEXT:-.tar.gz}"
  - export PKG="slacker-${VER}.${GOOS}_${GOARCH}${GOARM:+v${GOARM}}.${PKGEXT}"
  - if [[ $GOOS = "linux" || $GOARCH = "amd64" ]]; then go test -v ./...; fi
  - go build
    -ldflags="-s -w -X \"main.timestamp=${TIME}\" -X \"main.version=${VER}\""
    -o "slacker${EXT}"
  - $PKGCMD "${PKG}" "slacker${EXT}"

deploy:
  provider: releases
  api_key:
    secure: >
        Vapx2krBEg9Gc5uPLDYKC0Z4V008U2LSydRjgm/DxN5I62uT1H5/QkNhDAVaoizmpPJcF
        ZlIdlyxCkpVAuVG1kONgcccR+Jzib90ItiQrH309hWqP7X0IApw9FTz98hMWTJJn6EA9X
        Clo5wK/NcCKt9W4CJ+bM10UU3tg81IByyipjwaPuA1EVSaOIuWmKSnv+1USkx1+MZARhw
        Kr1S4fuVpNWVp8W7wBlP27VKN2K8pxc5xgO5JkYx6U5ONc2Y5uJX5QWPPcYVWgjqOKBUk
        ypSECTW0nTHPq4wiiCw+E/vpf13Zr0o6IDWvWBz3N6NJAMRZj8/94X1BoWt4W4mE0uSwc
        ngYQS4OYp0NSKdJgfNnpi9MY+Qfml+3gybNnCancT9bw7Ce3dd2lGnhIsxTMXtItbs3fR
        w2I0BnX933RhbUPzpQ4mde70Z3NdKbrG/o6I8gyw/CgjosLqB0PXpb6w2nqDzkKaRqYLu
        PVAqWcCVtgk4IG17xk2cBtR0uZsnxqBhBNmaOH9tcJBa9njYkN9kImmlnziKw4cH34scz
        6w0t9TUNxuxAmbSkdxeM1aRCE6TKM35GUnkZOJYoKt37FfMHbyrbxy1Qi6kGJWJ9pHj68
        VsmA2Rg8bdoNyeabJcu/vjM0FalMsyVeIIIP4egpIo0rmniZI2Y1+NGlqAqkR8=
  skip_cleanup: true
  file_glob: true
  file: ${PKG}
  "on":
    repo: logic/slacker
    tags: true
