---
os: linux

language: go

go:
  - 1.8.x

env:
  - MY_GOOS=darwin MY_GOARCH=386
  - MY_GOOS=darwin MY_GOARCH=amd64
  - MY_GOOS=dragonfly MY_GOARCH=amd64
  - MY_GOOS=freebsd MY_GOARCH=386
  - MY_GOOS=freebsd MY_GOARCH=amd64
  - MY_GOOS=freebsd MY_GOARCH=arm GOARM=6
  - MY_GOOS=freebsd MY_GOARCH=arm GOARM=7
  - MY_GOOS=freebsd MY_GOARCH=arm
  - MY_GOOS=linux MY_GOARCH=386
  - MY_GOOS=linux MY_GOARCH=amd64
  - MY_GOOS=linux MY_GOARCH=arm GOARM=5
  - MY_GOOS=linux MY_GOARCH=arm GOARM=6
  - MY_GOOS=linux MY_GOARCH=arm GOARM=7
  - MY_GOOS=linux MY_GOARCH=arm
  - MY_GOOS=linux MY_GOARCH=arm64
  - MY_GOOS=linux MY_GOARCH=mips64
  - MY_GOOS=linux MY_GOARCH=mips64le
  - MY_GOOS=linux MY_GOARCH=ppc64
  - MY_GOOS=linux MY_GOARCH=ppc64le
  - MY_GOOS=linux MY_GOARCH=s390x
  - MY_GOOS=netbsd MY_GOARCH=386
  - MY_GOOS=netbsd MY_GOARCH=amd64
  - MY_GOOS=netbsd MY_GOARCH=arm GOARM=6
  - MY_GOOS=netbsd MY_GOARCH=arm GOARM=7
  - MY_GOOS=netbsd MY_GOARCH=arm
  - MY_GOOS=openbsd MY_GOARCH=386
  - MY_GOOS=openbsd MY_GOARCH=amd64
  - MY_GOOS=openbsd MY_GOARCH=arm GOARM=6
  - MY_GOOS=openbsd MY_GOARCH=arm GOARM=7
  - MY_GOOS=openbsd MY_GOARCH=arm
  - MY_GOOS=solaris MY_GOARCH=amd64
  - MY_GOOS=windows MY_GOARCH=386 EXT=".exe" PKGCMD="zip -9" PKGEXT=".zip"
  - MY_GOOS=windows MY_GOARCH=amd64 EXT=".exe" PKGCMD="zip -9" PKGEXT=".zip"

install:
  - go get -t -v ./...

script:
  - export GOOS="${MY_GOOS}"
  - export GOARCH="${MY_GOARCH}"
  - export TIME="$(date +%Y-%m-%dT%H:%M:%S%z)"
  - export VER="${TRAVIS_TAG:-$TRAVIS_COMMIT}"
  - export PKGCMD="${PKGCMD:-tar zcvf}"
  - export PKGEXT="${PKGEXT:-.tar.gz}"
  - export PKG="slacker-${VER}.${GOOS}_${GOARCH}${GOARM:+v${GOARM}}.${PKGEXT}"
  - echo "travis_fold:start:ENV"
  - env
  - echo "travis_fold:end:ENV"
  - echo "travis_fold:start:TEST"
  - go test -v ./...
  - echo "travis_fold:end:TEST"
  - go build
    -ldflags="-s -w -X \"main.timestamp=${TIME}\" -X \"main.version=${VER}\""
    -o "slacker${EXT}"
  - $PKGCMD "${PKG}" "slacker${EXT}"
  - ls -l "slacker${EXT}" "${PKG}" &&  sha256sum "${PKG}"

deploy:
  provider: releases
  api_key:
    secure: >
        Vapx2krBEg9Gc5uPLDYKC0Z4V008U2LSydRjgm/DxN5I62uT1H5/QkNhDAVaoizmpPJcF
        ZlIdlyxCkpVAuVG1kONgcccR+Jzib90ItiQrH309hWqP7X0IApw9FTz98hMWTJJn6EA9X
        Clo5wK/NcCKt9W4CJ+bM10UU3tg81IByyipjwaPuA1EVSaOIuWmKSnv+1USkx1+MZARhw
        Kr1S4fuVpNWVp8W7wBlP27VKN2K8pxc5xgO5JkYx6U5ONc2Y5uJX5QWPPcYVWgjqOKBUk
        ypSECTW0nTHPq4wiiCw+E/vpf13Zr0o6IDWvWBz3N6NJAMRZj8/94X1BoWt4W4mE0uSwc
        ngYQS4OYp0NSKdJgfNnpi9MY+Qfml+3gybNnCancT9bw7Ce3dd2lGnhIsxTMXtItbs3fR
        w2I0BnX933RhbUPzpQ4mde70Z3NdKbrG/o6I8gyw/CgjosLqB0PXpb6w2nqDzkKaRqYLu
        PVAqWcCVtgk4IG17xk2cBtR0uZsnxqBhBNmaOH9tcJBa9njYkN9kImmlnziKw4cH34scz
        6w0t9TUNxuxAmbSkdxeM1aRCE6TKM35GUnkZOJYoKt37FfMHbyrbxy1Qi6kGJWJ9pHj68
        VsmA2Rg8bdoNyeabJcu/vjM0FalMsyVeIIIP4egpIo0rmniZI2Y1+NGlqAqkR8=
  skip_cleanup: true
  file_glob: true
  file: ${PKG}
  "on":
    repo: logic/slacker
    tags: true
